import type { OnboardingData } from './port-onboarding-wizard';

export function getSamplePortData(): OnboardingData {
  // Sample based on Port of Singapore
  return {
    port: {
      portName: 'Port of Singapore',
      portCode: 'SGSIN',
      unlocode: 'SGSIN',
      country: 'Singapore',
      timezone: 'Asia/Singapore',
      coordinates: {
        latitude: 1.2644,
        longitude: 103.8227,
      },
      contactEmail: 'operations@portofsingapore.com',
      contactPhone: '+65 6123 4567',
    },
    integration: {
      systemType: 'maritime_single_window',
      apiEndpoint: 'https://api.singaporemsw.gov.sg/v1',
      apiKey: '••••••••••••••••',
      dataSync: {
        vesselCalls: true,
        falForms: true,
        cargoManifest: true,
        crewLists: true,
      },
      syncFrequency: 'realtime',
    },
    terminals: [
      {
        id: 'T1',
        name: 'Pasir Panjang Terminal',
        code: 'PPT',
        terminalType: 'container',
        operatingCompany: 'PSA International',
        operationalHours: '24/7',
      },
      {
        id: 'T2',
        name: 'Brani Terminal',
        code: 'BRT',
        terminalType: 'container',
        operatingCompany: 'PSA International',
        operationalHours: '24/7',
      },
      {
        id: 'T3',
        name: 'Keppel Terminal',
        code: 'KPT',
        terminalType: 'container',
        operatingCompany: 'Keppel Terminals',
        operationalHours: '24/7',
      },
    ],
    berths: [
      // Pasir Panjang Terminal Berths
      {
        id: 'B1',
        terminalId: 'T1',
        name: 'PPT-1',
        length: 350,
        maxDraft: 16.0,
        maxLOA: 360,
        maxBeam: 52,
        maxDWT: 120000,
        bollards: 16,
        fenders: 24,
        reeferPoints: 150,
        freshWater: true,
        bunkering: true,
      },
      {
        id: 'B2',
        terminalId: 'T1',
        name: 'PPT-2',
        length: 350,
        maxDraft: 16.0,
        maxLOA: 360,
        maxBeam: 52,
        maxDWT: 120000,
        bollards: 16,
        fenders: 24,
        reeferPoints: 150,
        freshWater: true,
        bunkering: true,
      },
      {
        id: 'B3',
        terminalId: 'T1',
        name: 'PPT-3',
        length: 320,
        maxDraft: 15.5,
        maxLOA: 330,
        maxBeam: 50,
        maxDWT: 100000,
        bollards: 14,
        fenders: 20,
        reeferPoints: 120,
        freshWater: true,
        bunkering: false,
      },
      {
        id: 'B4',
        terminalId: 'T1',
        name: 'PPT-4',
        length: 320,
        maxDraft: 15.5,
        maxLOA: 330,
        maxBeam: 50,
        maxDWT: 100000,
        bollards: 14,
        fenders: 20,
        reeferPoints: 120,
        freshWater: true,
        bunkering: false,
      },
      // Brani Terminal Berths
      {
        id: 'B5',
        terminalId: 'T2',
        name: 'BRT-1',
        length: 300,
        maxDraft: 14.5,
        maxLOA: 310,
        maxBeam: 48,
        maxDWT: 90000,
        bollards: 12,
        fenders: 18,
        reeferPoints: 100,
        freshWater: true,
        bunkering: true,
      },
      {
        id: 'B6',
        terminalId: 'T2',
        name: 'BRT-2',
        length: 300,
        maxDraft: 14.5,
        maxLOA: 310,
        maxBeam: 48,
        maxDWT: 90000,
        bollards: 12,
        fenders: 18,
        reeferPoints: 100,
        freshWater: true,
        bunkering: false,
      },
      {
        id: 'B7',
        terminalId: 'T2',
        name: 'BRT-3',
        length: 280,
        maxDraft: 14.0,
        maxLOA: 290,
        maxBeam: 46,
        maxDWT: 80000,
        bollards: 12,
        fenders: 16,
        reeferPoints: 80,
        freshWater: true,
        bunkering: false,
      },
      {
        id: 'B8',
        terminalId: 'T2',
        name: 'BRT-4',
        length: 280,
        maxDraft: 14.0,
        maxLOA: 290,
        maxBeam: 46,
        maxDWT: 80000,
        bollards: 12,
        fenders: 16,
        reeferPoints: 80,
        freshWater: true,
        bunkering: false,
      },
      // Keppel Terminal Berths
      {
        id: 'B9',
        terminalId: 'T3',
        name: 'KPT-1',
        length: 340,
        maxDraft: 15.5,
        maxLOA: 350,
        maxBeam: 51,
        maxDWT: 110000,
        bollards: 15,
        fenders: 22,
        reeferPoints: 140,
        freshWater: true,
        bunkering: true,
      },
      {
        id: 'B10',
        terminalId: 'T3',
        name: 'KPT-2',
        length: 340,
        maxDraft: 15.5,
        maxLOA: 350,
        maxBeam: 51,
        maxDWT: 110000,
        bollards: 15,
        fenders: 22,
        reeferPoints: 140,
        freshWater: true,
        bunkering: true,
      },
      {
        id: 'B11',
        terminalId: 'T3',
        name: 'KPT-3',
        length: 310,
        maxDraft: 15.0,
        maxLOA: 320,
        maxBeam: 49,
        maxDWT: 95000,
        bollards: 14,
        fenders: 20,
        reeferPoints: 110,
        freshWater: true,
        bunkering: false,
      },
      {
        id: 'B12',
        terminalId: 'T3',
        name: 'KPT-4',
        length: 310,
        maxDraft: 15.0,
        maxLOA: 320,
        maxBeam: 49,
        maxDWT: 95000,
        bollards: 14,
        fenders: 20,
        reeferPoints: 110,
        freshWater: true,
        bunkering: false,
      },
    ],
    equipment: [
      // Pasir Panjang Terminal Equipment
      { id: 'E1', terminalId: 'T1', type: 'STS', name: 'STS-PPT-1', capacity: 65, status: 'operational' },
      { id: 'E2', terminalId: 'T1', type: 'STS', name: 'STS-PPT-2', capacity: 65, status: 'operational' },
      { id: 'E3', terminalId: 'T1', type: 'STS', name: 'STS-PPT-3', capacity: 65, status: 'operational' },
      { id: 'E4', terminalId: 'T1', type: 'STS', name: 'STS-PPT-4', capacity: 65, status: 'operational' },
      { id: 'E5', terminalId: 'T1', type: 'STS', name: 'STS-PPT-5', capacity: 65, status: 'operational' },
      { id: 'E6', terminalId: 'T1', type: 'STS', name: 'STS-PPT-6', capacity: 65, status: 'operational' },
      { id: 'E7', terminalId: 'T1', type: 'RTG', name: 'RTG-PPT-1', capacity: 45, status: 'operational' },
      { id: 'E8', terminalId: 'T1', type: 'RTG', name: 'RTG-PPT-2', capacity: 45, status: 'operational' },
      { id: 'E9', terminalId: 'T1', type: 'RTG', name: 'RTG-PPT-3', capacity: 45, status: 'operational' },
      { id: 'E10', terminalId: 'T1', type: 'RTG', name: 'RTG-PPT-4', capacity: 45, status: 'operational' },
      { id: 'E11', terminalId: 'T1', type: 'RTG', name: 'RTG-PPT-5', capacity: 45, status: 'operational' },
      { id: 'E12', terminalId: 'T1', type: 'RTG', name: 'RTG-PPT-6', capacity: 45, status: 'operational' },
      { id: 'E13', terminalId: 'T1', type: 'RTG', name: 'RTG-PPT-7', capacity: 45, status: 'operational' },
      { id: 'E14', terminalId: 'T1', type: 'RTG', name: 'RTG-PPT-8', capacity: 45, status: 'operational' },
      
      // Brani Terminal Equipment
      { id: 'E15', terminalId: 'T2', type: 'STS', name: 'STS-BRT-1', capacity: 60, status: 'operational' },
      { id: 'E16', terminalId: 'T2', type: 'STS', name: 'STS-BRT-2', capacity: 60, status: 'operational' },
      { id: 'E17', terminalId: 'T2', type: 'STS', name: 'STS-BRT-3', capacity: 60, status: 'operational' },
      { id: 'E18', terminalId: 'T2', type: 'STS', name: 'STS-BRT-4', capacity: 60, status: 'operational' },
      { id: 'E19', terminalId: 'T2', type: 'RTG', name: 'RTG-BRT-1', capacity: 40, status: 'operational' },
      { id: 'E20', terminalId: 'T2', type: 'RTG', name: 'RTG-BRT-2', capacity: 40, status: 'operational' },
      { id: 'E21', terminalId: 'T2', type: 'RTG', name: 'RTG-BRT-3', capacity: 40, status: 'operational' },
      { id: 'E22', terminalId: 'T2', type: 'RTG', name: 'RTG-BRT-4', capacity: 40, status: 'operational' },
      { id: 'E23', terminalId: 'T2', type: 'RTG', name: 'RTG-BRT-5', capacity: 40, status: 'operational' },
      { id: 'E24', terminalId: 'T2', type: 'RTG', name: 'RTG-BRT-6', capacity: 40, status: 'operational' },
      { id: 'E25', terminalId: 'T2', type: 'MHC', name: 'MHC-BRT-1', capacity: 100, status: 'operational' },
      { id: 'E26', terminalId: 'T2', type: 'MHC', name: 'MHC-BRT-2', capacity: 100, status: 'operational' },
      
      // Keppel Terminal Equipment
      { id: 'E27', terminalId: 'T3', type: 'STS', name: 'STS-KPT-1', capacity: 65, status: 'operational' },
      { id: 'E28', terminalId: 'T3', type: 'STS', name: 'STS-KPT-2', capacity: 65, status: 'operational' },
      { id: 'E29', terminalId: 'T3', type: 'STS', name: 'STS-KPT-3', capacity: 65, status: 'operational' },
      { id: 'E30', terminalId: 'T3', type: 'STS', name: 'STS-KPT-4', capacity: 65, status: 'operational' },
      { id: 'E31', terminalId: 'T3', type: 'STS', name: 'STS-KPT-5', capacity: 65, status: 'operational' },
      { id: 'E32', terminalId: 'T3', type: 'RTG', name: 'RTG-KPT-1', capacity: 45, status: 'operational' },
      { id: 'E33', terminalId: 'T3', type: 'RTG', name: 'RTG-KPT-2', capacity: 45, status: 'operational' },
      { id: 'E34', terminalId: 'T3', type: 'RTG', name: 'RTG-KPT-3', capacity: 45, status: 'operational' },
      { id: 'E35', terminalId: 'T3', type: 'RTG', name: 'RTG-KPT-4', capacity: 45, status: 'operational' },
      { id: 'E36', terminalId: 'T3', type: 'RTG', name: 'RTG-KPT-5', capacity: 45, status: 'operational' },
      { id: 'E37', terminalId: 'T3', type: 'RTG', name: 'RTG-KPT-6', capacity: 45, status: 'operational' },
      { id: 'E38', terminalId: 'T3', type: 'RTG', name: 'RTG-KPT-7', capacity: 45, status: 'operational' },
      { id: 'E39', terminalId: 'T3', type: 'RMG', name: 'RMG-KPT-1', capacity: 50, status: 'operational' },
      { id: 'E40', terminalId: 'T3', type: 'RMG', name: 'RMG-KPT-2', capacity: 50, status: 'operational' },
      { id: 'E41', terminalId: 'T3', type: 'RMG', name: 'RMG-KPT-3', capacity: 50, status: 'operational' },
      { id: 'E42', terminalId: 'T3', type: 'Reach Stacker', name: 'RS-KPT-1', capacity: 45, status: 'operational' },
      { id: 'E43', terminalId: 'T3', type: 'Reach Stacker', name: 'RS-KPT-2', capacity: 45, status: 'operational' },
      { id: 'E44', terminalId: 'T3', type: 'Reach Stacker', name: 'RS-KPT-3', capacity: 45, status: 'operational' },
      { id: 'E45', terminalId: 'T3', type: 'MHC', name: 'MHC-KPT-1', capacity: 100, status: 'operational' },
      { id: 'E46', terminalId: 'T3', type: 'MHC', name: 'MHC-KPT-2', capacity: 100, status: 'operational' },
    ],
    humanResources: [
      { role: 'Pilots', count: 24, shifts: 3, availability: '24/7' },
      { role: 'Tug Operators', count: 36, shifts: 3, availability: '24/7' },
      { role: 'Crane Operators', count: 92, shifts: 3, availability: '24/7' },
      { role: 'Ground Workers', count: 180, shifts: 3, availability: '24/7' },
      { role: 'Security Personnel', count: 48, shifts: 3, availability: '24/7' },
    ],
    constraints: [
      {
        id: 'C1',
        type: 'weather',
        name: 'Wind Speed Restriction',
        description: 'Crane operations suspended when wind speed exceeds safety threshold',
        threshold: '25 knots',
        action: 'Suspend STS crane operations',
      },
      {
        id: 'C2',
        type: 'tide',
        name: 'Low Tide Draft Restriction',
        description: 'Minimum water depth requirement for safe vessel entry and maneuvering',
        threshold: '14.0m minimum depth',
        action: 'Delay berthing until high tide',
      },
      {
        id: 'C3',
        type: 'environmental',
        name: 'Night-time Noise Restriction',
        description: 'Noise level limits during night hours to comply with environmental regulations',
        threshold: '22:00-06:00',
        action: 'Reduce cargo handling operations',
      },
      {
        id: 'C4',
        type: 'safety',
        name: 'Hazmat Segregation',
        description: 'Dangerous goods (IMDG Class 1) require minimum separation distance',
        threshold: 'IMDG Class 1: 50m separation',
        action: 'Allocate dedicated berth with buffer zone',
      },
      {
        id: 'C5',
        type: 'operational',
        name: 'Maximum Vessel LOA',
        description: 'Operational maximum for vessel length overall per berth',
        threshold: 'Varies by berth (280-360m)',
        action: 'Allocate to appropriate berth based on vessel size',
      },
      {
        id: 'C6',
        type: 'weather',
        name: 'Visibility Restriction',
        description: 'Minimum visibility required for safe vessel navigation',
        threshold: 'Less than 500m visibility',
        action: 'Delay arrival until visibility improves',
      },
    ],
  };
}
