-- =============================================
-- BERTH PLANNING SYSTEM - CLEAR ALL SEED DATA
-- Run this BEFORE inserting new seed data
-- Deletes in reverse FK dependency order
-- =============================================

USE [BerthPlanning];
GO

SET NOCOUNT ON;

PRINT '==============================================';
PRINT 'CLEARING ALL EXISTING SEED DATA';
PRINT '==============================================';

-- Disable FK checks temporarily
EXEC sp_MSforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL';

-- Delete in reverse FK dependency order
PRINT 'Deleting UKC_DATA...';
DELETE FROM UKC_DATA;

PRINT 'Deleting RESOURCE_ALLOCATION...';
DELETE FROM RESOURCE_ALLOCATION;

PRINT 'Deleting VESSEL_HISTORY...';
DELETE FROM VESSEL_HISTORY;

PRINT 'Deleting CONFLICTS...';
DELETE FROM CONFLICTS;

PRINT 'Deleting ALERTS_NOTIFICATIONS...';
DELETE FROM ALERTS_NOTIFICATIONS;

PRINT 'Deleting AUDIT_LOG...';
DELETE FROM AUDIT_LOG;

PRINT 'Deleting AIS_DATA...';
DELETE FROM AIS_DATA;

PRINT 'Deleting WEATHER_DATA...';
DELETE FROM WEATHER_DATA;

PRINT 'Deleting TIDAL_DATA...';
DELETE FROM TIDAL_DATA;

PRINT 'Deleting OPTIMIZATION_RUNS...';
DELETE FROM OPTIMIZATION_RUNS;

PRINT 'Deleting USER_PREFERENCES...';
DELETE FROM USER_PREFERENCES;

PRINT 'Deleting VESSEL_SCHEDULE...';
DELETE FROM VESSEL_SCHEDULE;

PRINT 'Deleting BERTH_MAINTENANCE...';
DELETE FROM BERTH_MAINTENANCE;

PRINT 'Deleting RESOURCES...';
DELETE FROM RESOURCES;

PRINT 'Deleting BERTHS...';
DELETE FROM BERTHS;

PRINT 'Deleting CHANNELS...';
DELETE FROM CHANNELS;

PRINT 'Deleting ANCHORAGES...';
DELETE FROM ANCHORAGES;

PRINT 'Deleting PILOTS...';
DELETE FROM PILOTS;

PRINT 'Deleting TUGBOATS...';
DELETE FROM TUGBOATS;

PRINT 'Deleting TERMINALS...';
DELETE FROM TERMINALS;

PRINT 'Deleting VESSELS...';
DELETE FROM VESSELS;

PRINT 'Deleting PORTS...';
DELETE FROM PORTS;

-- Re-enable FK checks
EXEC sp_MSforeachtable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL';

-- Reset identity seeds
PRINT '';
PRINT 'Resetting identity seeds...';

DBCC CHECKIDENT ('PORTS', RESEED, 0);
DBCC CHECKIDENT ('TERMINALS', RESEED, 0);
DBCC CHECKIDENT ('VESSELS', RESEED, 0);
DBCC CHECKIDENT ('BERTHS', RESEED, 0);
DBCC CHECKIDENT ('VESSEL_SCHEDULE', RESEED, 0);
DBCC CHECKIDENT ('RESOURCES', RESEED, 0);
DBCC CHECKIDENT ('RESOURCE_ALLOCATION', RESEED, 0);
DBCC CHECKIDENT ('WEATHER_DATA', RESEED, 0);
DBCC CHECKIDENT ('TIDAL_DATA', RESEED, 0);
DBCC CHECKIDENT ('AIS_DATA', RESEED, 0);
DBCC CHECKIDENT ('CONFLICTS', RESEED, 0);
DBCC CHECKIDENT ('OPTIMIZATION_RUNS', RESEED, 0);
DBCC CHECKIDENT ('VESSEL_HISTORY', RESEED, 0);
DBCC CHECKIDENT ('BERTH_MAINTENANCE', RESEED, 0);
DBCC CHECKIDENT ('ALERTS_NOTIFICATIONS', RESEED, 0);
DBCC CHECKIDENT ('USER_PREFERENCES', RESEED, 0);
DBCC CHECKIDENT ('AUDIT_LOG', RESEED, 0);
DBCC CHECKIDENT ('ANCHORAGES', RESEED, 0);
DBCC CHECKIDENT ('CHANNELS', RESEED, 0);
DBCC CHECKIDENT ('PILOTS', RESEED, 0);
DBCC CHECKIDENT ('TUGBOATS', RESEED, 0);
DBCC CHECKIDENT ('UKC_DATA', RESEED, 0);

PRINT '';
PRINT '==============================================';
PRINT 'ALL DATA CLEARED SUCCESSFULLY!';
PRINT '==============================================';
GO
